### ISSUE TITLE
很容易导致网络出错

### ISSUE THREAD

**Issue by billyosoror** [HibiKier/nonebot-plugin-zxreport#1]
经常出现httpx网络超时
![捕获](https://github.com/user-attachments/assets/3157f585-2fd0-4c54-8215-998c19a48018)
![捕获1](https://github.com/user-attachments/assets/fe1eaaac-c5b4-4e52-ac16-224bf93e5239)

**Comment by HibiKier** [comment]
检查下网络？https://api.bgm.tv/calendar，这个url访问基本没问题

**Comment by Jieshsa** [comment]
问题+1，curl能访问这个网站https://api.bgm.tv/calendar，
![image](https://github.com/user-attachments/assets/a4037d68-514c-48ee-9ed3-7d66104aa226)

**Comment by HibiKier** [comment]
现在一直连接超时吗

**Comment by billyosoror** [comment]
> 现在一直连接超时吗

是的，问题依旧存在，有尝试开科学上网和关闭科学上网并重启bot，但是依旧超时，浏览器是可以访问┭┮﹏┭┮
![f0627077-8878-4486-89fa-54f9f70b5755](https://github.com/user-attachments/assets/1f96df7b-ff96-49f7-a204-1ea027608f50)
![QQ20241019-193325](https://github.com/user-attachments/assets/8a1d9d2c-85bc-492c-a3a5-536ea89db2e0)

**Comment by HibiKier** [comment]
你这个超时不是访问这个url造成的吧，看着更像渲染html的时候报的，多试几次报错发完整点看看？

**Comment by Jieshsa** [comment]
[nb.log](https://github.com/user-attachments/files/17456544/nb.log)
完整的报错日志在这

**Comment by HibiKier** [comment]
更新一下试试，提高了url请求的超时时间

**Comment by Jieshsa** [comment]
还是不行，同样报错

**Comment by HibiKier** [comment]
最新版本使用alapi的早报api来替换60s看世界api，你可以通过在.env.dev中配置alapi token来设置，在https://admin.alapi.cn/user/login登录后获取token
