### ISSUE TITLE
无法触发真寻日报

### ISSUE THREAD

**Issue by saferabbit** [HibiKier/nonebot-plugin-zxreport#5]
无法触发真寻日报，但是重置真寻日报确正常，等很久也没有超时。

![image](https://github.com/user-attachments/assets/1cbea7e1-222c-41e9-b4f1-bb45388654fc)

**Comment by HibiKier** [comment]
你用的bot是真寻吗，如果是的话建议用真寻插件库的日报

**Comment by saferabbit** [comment]
是真寻bot，使用真寻插件库里的日报就正常了

**Comment by ZhanYiLiangRan** [comment]
> 你用的bot是真寻吗，如果是的话建议用真寻插件库的日报

您好，请问可以指路一下嘛
