### ISSUE TITLE
安装报错求助

### ISSUE THREAD

**Issue by ZhanYiLiangRan** [HibiKier/nonebot-plugin-zxreport#6]
![f00efaa98e78f29f79929b8080d5f2ff](https://github.com/user-attachments/assets/51662986-b257-4cf8-9cb8-0fee93512967)

**Comment by HibiKier** [comment]
提高你的nb版本至少到2.3.0+

**Comment by ZhanYiLiangRan** [comment]
> 提高你的nb版本至少到2.3.0+

好的，感谢
