### ISSUE TITLE
无法触发指令

### ISSUE THREAD

**Issue by ZhanYiLiangRan** [HibiKier/nonebot-plugin-zxreport#7]
使用“重置真寻日报”会正常回复“真寻日报已重置!”
但是使用“真寻日报”并没有任何回复
![1](https://github.com/user-attachments/assets/d46fc2b8-4b18-4a22-aed5-6e0c01baa76e)
![2](https://github.com/user-attachments/assets/52f8ab72-97e0-4b2e-bd47-84faafa0970d)

**Comment by HibiKier** [comment]
如果你是新版本真寻的话推荐去使用真寻插件库里的真寻日报，或者如下修改
```
_matcher = on_alconna(Alconna("真寻日报"), priority=5, block=True, use_origin=True)
```
将use_origin改为true

**Comment by ZhanYiLiangRan** [comment]
> 如果你是新版本真寻的话推荐去使用真寻插件库里的真寻日报，或者如下修改
> 
> ```
> _matcher = on_alconna(Alconna("真寻日报"), priority=5, block=True, use_origin=True)
> ```
> 
> 将use_origin改为true

感谢，现用的是0.1.6.7版本的真寻，修改代码后可以正常触发
